### ISSUE TITLE
Dont't run

### ISSUE THREAD

**Issue by phanthuthao** [monishmonish/exif-gps-tracer#1]
[+] Enter path for your dataset : /home/joker2020/Downloads/index.jpeg/
Traceback (most recent call last):
  File "/home/Makali/soft/exif-gps-tracer/plotmap.py", line 21, in <module>
    gps,time=getdata()
  File "/home/Makali/soft/exif-gps-tracer/getdata.py", line 6, in getdata
    file_data=scanfiles(path)
  File "/home/Makali/soft/exif-gps-tracer/scanfiles.py", line 6, in scanfiles
    fnames = os.listdir(path)
NotADirectoryError: [Errno 20] Not a directory: '/home/Makali/Downloads/index.jpeg/'

**Comment by m0n1x90** [comment]
Enter your dataset path only...not your image path
i.e:
/home/joker2020/Downloads/
(Dataset folder)

Not like this
/home/joker2020/Downloads/index.jpeg/

Your dataset folder should contain multiple images with exif data inorder to generate a map from your Google map API key
