### ISSUE TITLE
Wasn't working but I think I fixed it by doing this.

### ISSUE THREAD

**Issue by iccugs** [monishmonish/exif-gps-tracer#2]
So I scraped a bunch of photos, put it into a folder and then put the folder as the dataset and initially got this:

```
PS C:\Users\1\Documents\scripts\exif-gps-tracer> py plotmap.py

        #       #    # # ######       #     # #####   ####           #    #####    ##    ####  ###### #####
        #        #  #  # #            #       #    # #               #    #    #  #  #  #    # #      #    #
        #####     ##   # #####  ##### #  #### #    #  ####  #####    #    #    # #    # #      #####  #    #
        #         ##   # #            #     # #####       #          #    #####  ###### #      #      #####
        #        #  #  # #            #     # #      #    #          #    #   #  #    # #    # #      #   #
        ####### #    # # #             #####  #       ####           #    #    # #    #  ####  ###### #    #


[+] Enter path for your dataset : D:\1\2\3\
No EXIF metadata found for D:\1\2\3\/file1.jpg
Traceback (most recent call last):
  File "C:\Users\1\Documents\scripts\exif-gps-tracer\plotmap.py", line 21, in <module>
    gps,time=getdata()
  File "C:\Users\1\Documents\scripts\exif-gps-tracer\getdata.py", line 13, in getdata
    gpstags = get_gpstags(exif,filename)
  File "C:\Users\1\Documents\scripts\exif-gps-tracer\getexif.py", line 25, in get_gpstags
UnboundLocalError: local variable 'geotagging' referenced before assignment
```
Pretty much, it wasn't going to the next file.  I'm thinking it's because there was no exif data, so python bugged out when it tried to return the variable geotagging.  I simply went into the getexif.py file and added 'else: geotagging = 0' like this, so that the variable was given a value and python wouldn't freak out:

```
def get_gpstags(exif,filename):
    if not exif:
        print("No EXIF metadata found for "+filename)
    if exif:
        geotagging = {}
        for (idx, tag) in TAGS.items():
            if tag == 'GPSInfo':
                if idx not in exif:
                    print("No EXIF GeoTag found on "+filename)
                    break

                for (key, val) in GPSTAGS.items():
                    if key in exif[idx]:
                        geotagging[val] = exif[idx][key]
    else:
        geotagging = 0

    return geotagging
```

After this, it seemed to go through all the files (unfortunately no exif data in any of them so I couldn't test further).  Then the script printed this and stopped:

```
Data processed from the given datasets
CSV file created successfully...(tracedlocation.csv)
Traceback (most recent call last):
  File "C:\Users\1\Documents\scripts\exif-gps-tracer\plotmap.py", line 41, in <module>
    gmap = gmplot.GoogleMapPlotter(gps[l-1][0],gps[l-1][1],30,apikey=API_KEY)
  File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\site-packages\gmplot\gmplot.py", line 390, in __init__
    self.center = (float(lat), float(lng))
TypeError: float() argument must be a string or a number, not 'NoneType'
```

I'm guessing this is because there were no values for gps data that it could parse.  I'm guessing had there been GPS data, it would have finished up fine, but I don't have any pictures with exif data to test this on, unfortunately.  Otherwise, looks like a pretty cool program that you made.  Hopefully I'll be able to use it on something in the future (especially since I went out of my way to make a Google Maps Javascript API key).

**Comment by m0n1x90** [comment]
Yeah, It seems that the dataset does not contain GeoData Exif Tags...Try that with exif dataset and you will get a HTML output containing routed map for every location from that dataset. Thank you Buddy....
